#!/usr/bin/perl -w
# 1. Description 
#    this pearl script is used to generate usys.S(stub) at compile time, then usys.S is linked by the linker to the final ELF
#    One example of usys.S:
#      .global fork
#      fork:
#      li a7, SYS_fork //load immediate number to a7
#      ecall            //trap into supervisor mode, the trap handler will cope with context saving and args passing, refer to RISCV syscall ABI
#      ret               //go back to where fork() was called in user app
# 2. How it works with user src(e.g. "cat")
#    2.1 generate usys.S at compiling time
#    2.2 compile cat.c to cat.o; compile usys.S to usys.o. 
#    2.3 Linker sees:
#        - cat.o has a syscall, it wants to call read(), so in cat.o it wants a symbol "read"
#        - usys.o contains this global symbol ".global read"
#        - they get connected. So the declaration in user.h + implementation from usys.S = real syscall function.
#        Example: riscv64-unknown-elf-gcc -nostdlib -T user.ld -o _sh  sh.o printf.o ulib.o umalloc.o usys.o
# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");
